image: gitpod/workspace-dotnet

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 5000
    onOpen: ignore
  - port: 5001
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
#tasks:
#  - command: cd aspnetcoreapp/ && dotnet run --urls http://0.0.0.0:5001